[build]
  command = "REACT_APP_API_BASE=https://auroravoices-api.onrender.com/api npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_BASE = "https://auroravoices-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
